on:
  push:
    branches:
      - develop
name: ğŸš€ Deploy website on push
jobs:
  web-deploy:
    name: ğŸ‰ Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v4
      - name: ğŸ”§ Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: ğŸ“¦ Install backend dependencies
        run: npm install
      - name: ğŸ—ï¸ Build backend
        run: |
          npm run clean
          npm run build:server
      - name: ğŸ—ï¸ Build frontend
        run: |
          cd client
          npm install
          npm run build
          cd ..
      - name: ğŸ“‚ Prepare deployment folder
        run: |
          mkdir -p deploy
          cp -r dist/server deploy/
          cp -r client/build deploy/client
      - name: ğŸš€ Deploy to Namecheap
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: vocabfeeder-dev.johndeguise.com
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /vocabfeeder-dev.johndeguise.com/
